env:
  jest: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
ignorePatterns:
  - /dist/
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - "@typescript-eslint"
rules:
  "@typescript-eslint/no-unused-vars":
    - "error"
    - argsIgnorePattern: "^_.*$"
  "@typescript-eslint/no-non-null-assertion": "off"
